allow_hosts:
  - '*'

title: "Pi Dashboard"
theme: dark
color: slate

providers:
  openweathermap: d5f41e42d8d9b1c1f1894c09d85367d0
  weatherapi: YOUR_WEATHERAPI_API_KEY

layout:
  columns: 3
  width: 300
  gap: 20

experimental:
  disableLegacyWidgets: false