allow_hosts:
  - homepage.home

title: "Pi Dashboard"
theme: dark
color: slate

providers:
  openweathermap: "{{HOMEPAGE_VAR_OWM_KEY}}"
  weatherapi: YOUR_WEATHERAPI_API_KEY

layout:
  columns: 3
  width: 300
  gap: 20

experimental:
  disableLegacyWidgets: false