name: Deploy Updated Stack

on:
  push:
    branches:
      - main  # Triggered on push to main (e.g. Renovate merge)

jobs:
  deploy:
    name: Update and Restart Docker Compose Stack
    runs-on: [self-hosted, homelab]

    steps:
      - name: Pull latest images
        run: docker compose pull
        working-directory: /workdir

      - name: Restart stack
        run: docker compose up -d --no-build --remove-orphans
        working-directory: /workdir


